services:
  api:
    container_name: dev_api
    ports: 
      - 3000:3000
    environment: 
      - PGUSER=user
      - PGHOST=db
      - PGPASSWORD=password
      - PGDATABASE=mydb
      - PGPORT=5432
      - NODE_ENV=development
    depends_on:
      - db
    command: bash -c "npm install && npm run seedDev && npm run dev"

  db:
    container_name: dev_db
    volumes:
      - "dbdata:/var/lib/postgresql/data"
    environment: 
      - POSTGRES_DB=mydb
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
volumes:
  dbdata:
